--CREATE TABLES PER DATA MODELING
--1.TITLES TABLE AND SET PRIMARY KEY

CREATE TABLE titles (

	title_id VARCHAR(30) PRIMARY KEY NOT NULL,

	title VARCHAR(100) NOT NULL

	
);

--2.EMPLOYEES TABLE AND SET PRIMARY KEY, FOREIGN KEY WITH REFERENCE

CREATE TABLE employees (

	emp_no INT PRIMARY KEY NOT NULL,

	emp_title_id VARCHAR(30) NOT NULL, 

	birth_date DATE NOT NULL,

	first_name VARCHAR(30) NOT NULL,

	last_name VARCHAR(30) NOT NULL,

	sex VARCHAR(1) NOT NULL,

	hire_date DATE NOT NULL,
	
	FOREIGN KEY (emp_title_id) REFERENCES titles (title_id)

);

--3.SALARIES TABLE AND SET PRIMARY KEY, FOREIGN KEY WITH REFERENCES

CREATE TABLE salaries (

	emp_no INT PRIMARY KEY NOT NULL,

	salary INT NOT NULL,

	FOREIGN KEY (emp_no) REFERENCES employees (emp_no)

);


--4.DEPARTMENTS TABLE AND SET PRIMARY KEY

CREATE TABLE departments (

	dept_no VARCHAR(10) PRIMARY KEY NOT NULL,

	dept_name VARCHAR(100) NOT NULL

	
);

--5.DEPT_MANAGER TABLE AND FOREIGN KEYS WITH REFERENCES

CREATE TABLE dept_manager (

	emp_no INT NOT NULL,
	
	dept_no VARCHAR(10) PRIMARY KEY NOT NULL,

	FOREIGN KEY (dept_no) REFERENCES departments (dept_no),

	FOREIGN KEY (emp_no) REFERENCES employees (emp_no)

);


--6.DEPT_EMP TABLE AND FOREIGN KEYS WITH REFERENCES

CREATE TABLE dept_emp (

	emp_no INT NOT NULL,

	dept_no VARCHAR(10) PRIMARY KEY NOT NULL,

	FOREIGN KEY (emp_no) REFERENCES employees (emp_no),

	FOREIGN KEY (dept_no) REFERENCES departments (dept_no)

);

